name: Deploy Kaapi to EC2 Staging

on:
  push:
    branches:
      - main # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS_STAGING_ENV

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM
        env:
          BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
          APP_NAME: ${{ secrets.PM2_APP_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["export HOME=/home/ubuntu && export PATH=/data/.nvm/versions/node/v24.11.0/bin:$PATH && git config --global --add safe.directory $BUILD_DIRECTORY && set -e && cd $BUILD_DIRECTORY && git pull origin main && npm ci && npm run build && su - ec2-user && pm2 restart $APP_NAME"]' \
            --region $AWS_REGION
